### ISSUE TITLE
IPv6 has something wrong under HE tunnelbroker

### ISSUE THREAD

**Issue by ii404msn** [MSF-Jarvis/wireguard-kt#97]
Same as WireGuard official Android Client...

Other Client can Ping the Android Client, Android Client can't Ping others.
Look like IPv6 no route..

My Win10 an iOS use TunSafe work will...

or, maybe it's the GoBackend bug...

**Comment by MSF-Jarvis** [comment]
Are you sure it's not a provider related issue? [Mullvad](https://mullvad.net)'s WireGuard servers give me both IPv4 and IPv6 addresses just fine.

https://i.imgur.com/xyaQ3S5.png

**Comment by ii404msn** [comment]
Win10 and iOS work fine. (tunsafe)
My VPS use IPv6 tunnel.    https://tunnelbroker.net
This is different from native IPv6,  maybe the problem is here.

**Comment by MSF-Jarvis** [comment]
Tunsafe is not really an upstanding example...

I can't really test this since all my networks are fully IPv6 enabled. Try the WireGuard [mailing list](https://lists.zx2c4.com/mailman/listinfo/wireguard) where you'll find people more well versed in low level network setups that can help debug the issue. Closing this now since it clearly isn't a problem with WireGuard-KT.

**Comment by ii404msn** [comment]
I try update my Lineageos, the problem is solved.
Thank you~
